@api = http://localhost:5000

GET  {{api}}/videos

###
GET http://localhost:5000/videos/621e6b726ef186825f5c1244

###
POST {{api}}/videos
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=tttSZZOwvNo&ab_channel=JeuzMusicBeats",
    "title": "pista",
    "description": "Es miedo que le tienen a la greña? wa wa wa"
}

###
DELETE {{api}}/videos/6220d5741de5731569a76376

###
PUT {{api}}/videos/621e70b8c3a65aaad2e4fa9c
Content-Type: application/json

{
    "title": "Dembow"
}